### ISSUE TITLE
Getting "Your browser is unsupported" errors as of 2017-11-08 in Google, GitHub

### ISSUE THREAD

**Issue by wohali** [LeoTindall/randomua#1]
Hi there,

Starting to get errors today that I haven't seen previously, when accessing Google Docs/Sheets and GitHub.

![mwsnap 2017-11-08 13_27_26](https://user-images.githubusercontent.com/112292/32567200-9343a5d4-c488-11e7-8f4f-8feacb01905c.png)

This is leading to subtle problems, such as the issue form on GH not working correctly sometimes (comment/issue is filed but page does not refresh correctly).

**Comment by wohali** [comment]
Forgot to say: FF 56.0.2, 64-bit, Windows 7.

**Comment by NoraCodes** [comment]
I'm going to add a setting for min and max spoofed version, which should fix this issue. Thanks for reporting it!

**Comment by NoraCodes** [comment]
1.1.0 now has a setting to let you set the minimum and maximum version. Set it to your current version (56) for min and then slowly lower it. For me, around 45 is a good balance.

Unfortunately, errors like this are the cost of using a randomized UA on the modern web. Sorry about that :(

**Comment by wohali** [comment]
Thanks for the feature - this is perfect.
