### ISSUE TITLE
I can't reset the user agent

### ISSUE THREAD

**Issue by anonsubmitter** [LeoTindall/randomua#2]
After I installed RandomUA I can't download some add-ons from AMO since AMO now thinks I use Firefox 52. I tried excluding addons.mozilla.org (didn't work), setting the minimum spoofer version to 53 (didn't work), deactivating RandomUA (didn't work), removing RandomUA (didn't work), and [resetting the user agent via about:config](https://support.mozilla.org/en-US/kb/how-reset-default-user-agent-firefox) (none of the values had been modified). Any idea on how to reset the user agent?

**Comment by anonsubmitter** [comment]
I managed to change it back to what I think is the original user agent using the [Modify Header Value (HTTP Headers)](https://addons.mozilla.org/firefox/addon/modify-header-value/) add-on. However, [BrowserLeaks.com](https://browserleaks.com/ip) still thinks that it's Firefox 52 and AMO just displays blank pages now. I can log in on Slack and Trello now though, which was not possible with the Firefox 52 user agent.

**Comment by NoraCodes** [comment]
RandomUA does not change the browser's configured UA header; it hooks each request and changes it dynamically.

Did you perhaps set the `about:config` option `privacy.resistFingerprinting`? That sets the UA to Firefox 52.

**Comment by anonsubmitter** [comment]
Yes, that was it (I should have looked into what `privacy.resistFingerprinting` did before activating it). Thanks for the help!
